// =====================================================================
// APB5_Top
//
// Structural wrapper that connects:
//    Requester  <-->  Interconnect  <-->  Completer[0 .. NUM_of_Completers-1]
//
// Check_Type is now a top-level parameter: set it to 1 to enable
// interface parity checking end-to-end, or 0 to disable it. When
// enabled, all the *CHK signals are wired between blocks following
// the same topology as the functional signals:
//   - Request-side checks (PADDR/PCTRL/PWAKEUP/PSTRB/PENABLE/PWDATA/
//     PAUSER/PWUSER) are generated by the Requester and broadcast
//     directly to every Completer, exactly like the payload signals
//     they protect - checked by each Completer's o_parity_err.
//   - PSELx/PSELxCHK are generated by the Interconnect and sent to
//     each Completer, also checked by that Completer's o_parity_err.
//   - Response-side checks from each Completer (PREADY/PRDATA/PSLVERR/
//     PRUSER/PBUSER CHK) are checked by the Interconnect
//     (o_hop1_parity_err) for the Completer -> Interconnect hop.
//   - The Interconnect regenerates its own checks for the muxed
//     response it forwards to the Requester, which checks them via
//     its own o_parity_err for the Interconnect -> Requester hop.
//
// The three block-level error outputs are brought out to the external
// interface:
//    o_requester_parity_err     <- Requester.o_parity_err
//    o_interconnect_parity_err  <- Interconnect.o_hop1_parity_err
//    o_completer_parity_err[c]  <- Completer[c].o_parity_err
// =====================================================================

module APB5_Top #(
    parameter int ADDR_WIDTH        = 32,
    parameter int DATA_WIDTH        = 32,
    parameter bit Wakeup_Signal     = 1,
    parameter int USER_REQ_WIDTH    = 1,
    parameter int USER_DATA_WIDTH   = 1,
    parameter int USER_RESP_WIDTH   = 1,
    parameter int WAIT_STATES_NUM   = 2,
    parameter int NUM_of_Completers = 2,
    parameter bit Check_Type        = 0   // enable/disable parity checking 
)
(
    input  logic                              PCLK,
    input  logic                              PRESETn,

    ///////////////////////////////////////////////////////
    //////////////// NATIVE REQUESTER-SIDE PORT ////////////
    ///////////////////////////////////////////////////////
    input  logic                              i_valid,
    input  logic [ADDR_WIDTH - 1 : 0]         i_addr,
    input  logic [2:0]                        i_prot,
    input  logic                              i_write,
    input  logic [DATA_WIDTH - 1 : 0]         i_wdata,
    input  logic [DATA_WIDTH/8 - 1 : 0]       i_strb,
    input  logic [USER_REQ_WIDTH - 1 : 0]     i_auser,
    input  logic [USER_DATA_WIDTH - 1 : 0]    i_wuser,

    output logic                              o_ready,
    output logic [DATA_WIDTH - 1 : 0]         o_rdata,
    output logic                              o_slverr,
    output logic [USER_RESP_WIDTH - 1 : 0]    o_buser,
    output logic [USER_DATA_WIDTH - 1 : 0]    o_ruser,

    ///////////////////////////////////////////////////////
    //////// COMPLETER <--> PERIPHERAL, per Completer //////
    ///////////////////////////////////////////////////////
    input  logic [USER_RESP_WIDTH - 1 : 0]    i_periph_PBUSER  [NUM_of_Completers],
    input  logic [USER_DATA_WIDTH - 1 : 0]    i_periph_PRUSER  [NUM_of_Completers],
    input  logic [DATA_WIDTH - 1 : 0]         i_periph_PRDATA  [NUM_of_Completers],
    input  logic                              i_periph_PSLVERR [NUM_of_Completers],

    output logic [2:0]                        o_periph_PPROT   [NUM_of_Completers],
    output logic [DATA_WIDTH - 1 : 0]         o_periph_PWDATA  [NUM_of_Completers],
    output logic [USER_REQ_WIDTH - 1 : 0]     o_periph_PAUSER  [NUM_of_Completers],
    output logic [USER_DATA_WIDTH - 1 : 0]    o_periph_PWUSER  [NUM_of_Completers],
    output logic [ADDR_WIDTH - 1 : 0]         o_periph_PADDR   [NUM_of_Completers],

    ///////////////////////////////////////////////////////
    //////////////// ERROR OUTPUTS (EXTERNAL) //////////////
    ///////////////////////////////////////////////////////
    output logic                              o_requester_parity_err,
    output logic                              o_interconnect_parity_err,
    output logic [NUM_of_Completers - 1 : 0]  o_completer_parity_err
);

    ///////////////////////////////////////////////////////
    ///////////////// REQUESTER <-> INTERCONNECT ///////////
    ///////////////////////////////////////////////////////
    logic [ADDR_WIDTH - 1 : 0]        w_PADDR;
    logic [2:0]                       w_PPROT;
    logic                             w_PSEL;
    logic                             w_PENABLE;
    logic                             w_PWRITE;
    logic [DATA_WIDTH - 1 : 0]        w_PWDATA;
    logic [DATA_WIDTH/8 - 1 : 0]      w_PSTRB;
    logic                             w_PWAKEUP;
    logic [USER_REQ_WIDTH - 1 : 0]    w_PAUSER;
    logic [USER_DATA_WIDTH - 1 : 0]   w_PWUSER;

    logic [DATA_WIDTH - 1 : 0]        w_PRDATA;
    logic                             w_PREADY;
    logic                             w_PSLVERR;
    logic [USER_RESP_WIDTH - 1 : 0]   w_PBUSER;
    logic [USER_DATA_WIDTH - 1 : 0]   w_PRUSER;

    ///////////////////////////////////////////////////////
    ////////// REQUESTER-GENERATED REQUEST-SIDE CHK ////////
    //////////  (broadcast to every Completer, like  ///////
    //////////   the payload signals they protect)   ///////
    ///////////////////////////////////////////////////////
    logic [(ADDR_WIDTH + 7)/8 - 1 : 0]        w_PADDRCHK;
    logic                                     w_PSELCHK;   
    logic                                     w_PENABLECHK;
    logic [(DATA_WIDTH + 7)/8 - 1 : 0]        w_PWDATACHK;
    logic                                     w_PSTRBCHK;
    logic                                     w_PWAKEUPCHK;
    logic [(USER_REQ_WIDTH + 7)/8 - 1 : 0]    w_PAUSERCHK;
    logic [(USER_DATA_WIDTH + 7)/8 - 1 : 0]   w_PWUSERCHK;
    logic                                     w_PCTRLCHK;

    ///////////////////////////////////////////////////////
    ////////// INTERCONNECT -> REQUESTER RESPONSE CHK //////
    ///////////////////////////////////////////////////////
    logic                                     w_PREADYCHK;
    logic [(DATA_WIDTH + 7)/8 - 1 : 0]        w_PRDATACHK;
    logic                                     w_PSLVERRCHK;
    logic [(USER_DATA_WIDTH + 7)/8 - 1 : 0]   w_PRUSERCHK;
    logic [(USER_RESP_WIDTH + 7)/8 - 1 : 0]   w_PBUSERCHK;

    ///////////////////////////////////////////////////////
    /////////////// INTERCONNECT <-> COMPLETERS ////////////
    ///////////////////////////////////////////////////////
    logic [NUM_of_Completers - 1 : 0]                             w_PSELx;
    logic [NUM_of_Completers - 1 : 0]                             w_PSELxCHK;

    logic [NUM_of_Completers - 1 : 0] [DATA_WIDTH - 1 : 0]        w_c_PRDATA;
    logic [NUM_of_Completers - 1 : 0]                             w_c_PREADY;
    logic [NUM_of_Completers - 1 : 0]                             w_c_PSLVERR;
    logic [NUM_of_Completers - 1 : 0] [USER_RESP_WIDTH - 1 : 0]   w_c_PBUSER;
    logic [NUM_of_Completers - 1 : 0] [USER_DATA_WIDTH - 1 : 0]   w_c_PRUSER;

    logic [NUM_of_Completers - 1 : 0]                             w_c_PREADYCHK;
    logic [NUM_of_Completers - 1 : 0] [(DATA_WIDTH + 7)/8 - 1:0]  w_c_PRDATACHK;
    logic [NUM_of_Completers - 1 : 0]                             w_c_PSLVERRCHK;
    logic [NUM_of_Completers - 1 : 0] [(USER_DATA_WIDTH+7)/8-1:0] w_c_PRUSERCHK;
    logic [NUM_of_Completers - 1 : 0] [(USER_RESP_WIDTH+7)/8-1:0] w_c_PBUSERCHK;

    ///////////////////////////////////////////////////////
    ///////////////////// REQUESTER ////////////////////////
    ///////////////////////////////////////////////////////
    Requester #(
        .ADDR_WIDTH      (ADDR_WIDTH),
        .DATA_WIDTH      (DATA_WIDTH),
        .Wakeup_Signal   (Wakeup_Signal),
        .USER_REQ_WIDTH  (USER_REQ_WIDTH),
        .USER_DATA_WIDTH (USER_DATA_WIDTH),
        .USER_RESP_WIDTH (USER_RESP_WIDTH),
        .Check_Type      (Check_Type)
    ) u_Requester (
        .PCLK      (PCLK),
        .PRESETn   (PRESETn),

        .i_valid   (i_valid),
        .i_addr    (i_addr),
        .i_prot    (i_prot),
        .i_write   (i_write),
        .i_wdata   (i_wdata),
        .i_strb    (i_strb),
        .i_auser   (i_auser),
        .i_wuser   (i_wuser),

        .o_ready   (o_ready),
        .o_rdata   (o_rdata),
        .o_slverr  (o_slverr),
        .o_buser   (o_buser),
        .o_ruser   (o_ruser),

        .PRDATA    (w_PRDATA),
        .PREADY    (w_PREADY),
        .PSLVERR   (w_PSLVERR),
        .PBUSER    (w_PBUSER),
        .PRUSER    (w_PRUSER),

        .PADDR     (w_PADDR),
        .PPROT     (w_PPROT),
        .PSEL      (w_PSEL),
        .PENABLE   (w_PENABLE),
        .PWRITE    (w_PWRITE),
        .PWDATA    (w_PWDATA),
        .PSTRB     (w_PSTRB),
        .PWAKEUP   (w_PWAKEUP),
        .PAUSER    (w_PAUSER),
        .PWUSER    (w_PWUSER),

        // response-side checks coming from the Interconnect
        .PREADYCHK  (w_PREADYCHK),
        .PRDATACHK  (w_PRDATACHK),
        .PSLVERRCHK (w_PSLVERRCHK),
        .PRUSERCHK  (w_PRUSERCHK),
        .PBUSERCHK  (w_PBUSERCHK),

        .o_parity_err (o_requester_parity_err),

        // request-side checks generated here, fanned out below
        .PADDRCHK    (w_PADDRCHK),
        .PSELCHK     (w_PSELCHK),
        .PENABLECHK  (w_PENABLECHK),
        .PWDATACHK   (w_PWDATACHK),
        .PSTRBCHK    (w_PSTRBCHK),
        .PWAKEUPCHK  (w_PWAKEUPCHK),
        .PAUSERCHK   (w_PAUSERCHK),
        .PWUSERCHK   (w_PWUSERCHK),
        .PCTRLCHK    (w_PCTRLCHK)
    );

    ///////////////////////////////////////////////////////
    ///////////////////// INTERCONNECT /////////////////////
    ///////////////////////////////////////////////////////
    Interconnect #(
        .ADDR_WIDTH        (ADDR_WIDTH),
        .DATA_WIDTH        (DATA_WIDTH),
        .USER_DATA_WIDTH   (USER_DATA_WIDTH),
        .USER_RESP_WIDTH   (USER_RESP_WIDTH),
        .Check_Type        (Check_Type),
        .NUM_of_Completers (NUM_of_Completers)
    ) u_Interconnect (
        .PSELx     (w_PSELx),
        .PSELxCHK  (w_PSELxCHK),

        .i_PRDATA  (w_c_PRDATA),
        .i_PREADY  (w_c_PREADY),
        .i_PSLVERR (w_c_PSLVERR),
        .i_PBUSER  (w_c_PBUSER),
        .i_PRUSER  (w_c_PRUSER),

        // response checks coming back from each Completer
        .i_PREADYCHK  (w_c_PREADYCHK),
        .i_PRDATACHK  (w_c_PRDATACHK),
        .i_PSLVERRCHK (w_c_PSLVERRCHK),
        .i_PRUSERCHK  (w_c_PRUSERCHK),
        .i_PBUSERCHK  (w_c_PBUSERCHK),

        .PADDR     (w_PADDR),
        .PSEL      (w_PSEL),
        .PENABLE   (w_PENABLE),
        .PWRITE    (w_PWRITE),

        .PRDATA    (w_PRDATA),
        .PREADY    (w_PREADY),
        .PSLVERR   (w_PSLVERR),
        .PBUSER    (w_PBUSER),
        .PRUSER    (w_PRUSER),

        // re-generated checks for the hop back to the Requester
        .PREADYCHK  (w_PREADYCHK),
        .PRDATACHK  (w_PRDATACHK),
        .PSLVERRCHK (w_PSLVERRCHK),
        .PRUSERCHK  (w_PRUSERCHK),
        .PBUSERCHK  (w_PBUSERCHK),

        .o_hop1_parity_err (o_interconnect_parity_err)
    );

    ///////////////////////////////////////////////////////
    ///////////////////// COMPLETERS ////////////////////////
    ///////////////////////////////////////////////////////
    generate
        for (genvar c = 0; c < NUM_of_Completers; c++) begin : g_completer

            Completer #(
                .ADDR_WIDTH      (ADDR_WIDTH),
                .DATA_WIDTH      (DATA_WIDTH),
                .Wakeup_Signal   (Wakeup_Signal),
                .USER_REQ_WIDTH  (USER_REQ_WIDTH),
                .USER_DATA_WIDTH (USER_DATA_WIDTH),
                .USER_RESP_WIDTH (USER_RESP_WIDTH),
                .Check_Type      (Check_Type),
                .WAIT_STATES_NUM (WAIT_STATES_NUM)
            ) u_Completer (
                .PCLK       (PCLK),
                .PRESETn    (PRESETn),

                .i_PADDR    (w_PADDR),
                .i_PADDRCHK (w_PADDRCHK),

                .PSELx      (w_PSELx[c]),
                .PSELxCHK   (w_PSELxCHK[c]),

                .PRDATA     (w_c_PRDATA[c]),
                .PREADY     (w_c_PREADY[c]),
                .PSLVERR    (w_c_PSLVERR[c]),
                .PBUSER     (w_c_PBUSER[c]),
                .PRUSER     (w_c_PRUSER[c]),

                // response-side checks generated here, sent to the Interconnect
                .PREADYCHK  (w_c_PREADYCHK[c]),
                .PRDATACHK  (w_c_PRDATACHK[c]),
                .PSLVERRCHK (w_c_PSLVERRCHK[c]),
                .PRUSERCHK  (w_c_PRUSERCHK[c]),
                .PBUSERCHK  (w_c_PBUSERCHK[c]),

                .PWAKEUP     (w_PWAKEUP),
                .PSTRB       (w_PSTRB),
                .PENABLE     (w_PENABLE),
                .PWAKEUPCHK  (w_PWAKEUPCHK),
                .PSTRBCHK    (w_PSTRBCHK),
                .PENABLECHK  (w_PENABLECHK),

                .i_PPROT     (w_PPROT),
                .i_PWRITE    (w_PWRITE),
                .i_PWDATA    (w_PWDATA),
                .i_PAUSER    (w_PAUSER),
                .i_PWUSER    (w_PWUSER),

                .i_PWDATACHK (w_PWDATACHK),
                .i_PAUSERCHK (w_PAUSERCHK),
                .i_PWUSERCHK (w_PWUSERCHK),
                .i_PCTRLCHK  (w_PCTRLCHK),

                // --- real peripheral connection for this Completer ---
                .i_PBUSER    (i_periph_PBUSER[c]),
                .i_PRUSER    (i_periph_PRUSER[c]),
                .i_PRDATA    (i_periph_PRDATA[c]),
                .i_PSLVERR   (i_periph_PSLVERR[c]),

                .PPROT       (o_periph_PPROT[c]),
                .PWDATA      (o_periph_PWDATA[c]),
                .PAUSER      (o_periph_PAUSER[c]),
                .PWUSER      (o_periph_PWUSER[c]),
                .PADDR       (o_periph_PADDR[c]),

                .o_parity_err (o_completer_parity_err[c])
            );

        end
    endgenerate

endmodule